Fotolog/config/routes.rb
Rails.application.routes.draw do
  resources :followers, only: [:create, :destroy, :delete, :index]
  get '/perfil/:id', to: 'perfil#show', as: 'perfil'

  resources :fotos do 
    resources :coments, only: [:create, :destroy, :index, :delete]
    resources :calificacions, only: [:create, :destroy, :index, :delete]

  end 
  devise_for :users

   root 'principal#index'

end

Fotolog/app/models/foto.rb
class Foto < ActiveRecord::Base
  belongs_to :user
  has_many :calificacions, dependent: :destroy
  has_many :coments, dependent: :destroy
  has_attached_file :imagen, styles: {medium: "800x600"}
  validates_attachment_content_type :imagen, content_type: /image/
  before_create :set_comentarios, :set_time
  validates :imagen, presence: true
  validates :descripcion, presence: true

  scope :ultimos,->{order("fecha_foto DESC")}

  def self.search(search)
    if search
      self.where('n_comentarios LIKE ?', "%#{search}%")
    else
      self.all
    end
  end


  def agregar_puntuacion(increment)
    self.increment!(:puntuacion_total, increment)
  end


  def agregar_comentarios
    self.update(n_comentarios: self.n_comentarios + 1)
    
  end


  def borrar_comentarios
    self.update(n_comentarios: self.n_comentarios - 1)
    
  end


  private
  
  def set_comentarios
  	self.n_comentarios=0
  end

  def set_time
  	self.fecha_foto=DateTime.now
  	
  end


end

Fotolog/app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:create, :show]
  before_action :just_user!, only: [:create, :new]
  before_action :validar_fotos_diarias! , only: [:create, :new]
  helper_method :sort_column, :sort_direction  
  # GET /fotos
  # GET /fotos.json
  def index
    if current_user.try(:is_admin?)
      @fotos = Foto.search(params[:search]).order("#{sort_column} #{sort_direction}") 
    else
      @fotos = current_user.fotos.ultimos
    end
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
    @coment= Coment.new
    @calificacion = Calificacion.new
  end

  # GET /fotos/new
  def new
      @foto = Foto.new
   
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create

      @foto = current_user.fotos.new(foto_params)

      respond_to do |format|
        if @foto.save
          format.html { redirect_to @foto, notice: 'La foto fue creada con exito.' }
          format.json { render :show, status: :created, location: @foto }
          @foto.user.fotos_diarias_usuario

        else
          format.html { render :new }
          format.json { render json: @foto.errors, status: :unprocessable_entity }
        end
      end

  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'La foto fue editada con exito.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'La foto fue eliminada con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:user_id, :fecha_foto, :descripcion, :n_comentarios, :imagen)
    end

    def validate_user
      redirect_to new_user_session_path, notice:"Necesitas iniciar sesion"      
    end

    def sort_column  
      Foto.column_names.include?(params[:sort]) ? params[:sort] : "id"    
    end  
      
    def sort_direction  
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"  
    end  
end

Fotolog/app/helpers/fotos_helper.rb
module FotosHelper

end

Fotolog/app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field" >
    Portada: <%= f.file_field :imagen %>
  </div>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Fotolog/app/views/fotos/edit.html.erb
<h1>Editing Foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

Fotolog/app/views/fotos/index.html.erb
<h1>Lista Fotos</h1>

<%= form_tag fotos_path, :method => 'get' do %>  
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :n_comentarios => nil %>
  </p>
<% end %>

<table >
  <thead>
    <tr>
  <th><%= link_to "Usuario", :sort => "user_id" %></th>  
  <th><%= sortable "n_comentarios" %></th>  
  <th><%= sortable "fecha_foto", "Fecha" %></th>  
  <th><%= sortable "puntuacion_total", "Puntaje" %></th>  

      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <% unless foto.user.nil? %>
        <td><%= foto.user.email %></td>
        <% end %>
        <td><center><%= foto.n_comentarios %></center></td>
        <td><%= foto.fecha_foto %></td>
        <td><%= foto.puntuacion_total %></td>

        <td><%= link_to 'Mostrar', foto %></td>
        <% if not current_user.is_admin? %>
        <td><%= link_to 'Editar', edit_foto_path(foto) %></td>
        <% end %>
        <td><%= link_to 'Eliminar', foto, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        <% if current_user.is_admin? %>
        <td><%= link_to 'Comentarios',foto_coments_path(foto.id) %></td>
        <% end %>


      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.is_admin?%>
<% else %>
  <h3>Numero de fotos publicadas hoy: <%= current_user.fotos_diarias %></h3> 

  <% if current_user.fotos_diarias<5%>
    <%= link_to 'Nueva Foto', new_foto_path %>
    <% else %>
    <h3>Excediste el limite de fotos diarias</h3> 

  <% end %>
<% end %>

Fotolog/app/views/fotos/new.html.erb
<h1>Nueva Foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

Fotolog/app/views/fotos/show.html.erb
	<% unless @foto.user.nil? %>
	<p>
	  <strong>Publicado por :</strong>
	  <%= @foto.user.email %>
	</p>
	<% end %>
	<div class="field">
		<%= image_tag @foto.imagen.url(:medium)%>
	</div>
	<p>
	  <strong>Fecha foto:</strong>
	  <%= @foto.fecha_foto %>
	</p>

	<p>
	  <strong>Descripcion:</strong>
	  <%= @foto.descripcion %>
	</p>

	<p>
	  <strong>N comentarios:</strong>
	  <%= @foto.n_comentarios %>
	</p>

	<p>
	  <strong>Puntuacion:</strong>
	  <%= @foto.puntuacion_total %>
	</p>
<% if user_signed_in? && @foto.user.email == current_user.email %>
<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>
<% end %>
<div>
	<h3>Evaluacion</h3>
	<%= render "calificacions/form" %>

</div>
<div>
	<h3>Comentarios</h3>	
	<% if @foto.n_comentarios<20 %>
	<%= render "coments/form" %>
	<% end %>
	<ul>
		<% @foto.coments.each do |coment| %>
		
		<li><%= coment.anonimo %> - <%= coment.fecha_comentario %> - <%= coment.texto_comentario %>  </li>
		<% end %>

	</ul>
</div>