Fotolog/config/routes.rb
Rails.application.routes.draw do
  resources :followers, only: [:create, :destroy, :delete, :index]
  get '/perfil/:id', to: 'perfil#show', as: 'perfil'

  resources :fotos do 
    resources :coments, only: [:create, :destroy, :index, :delete]
    resources :calificacions, only: [:create, :destroy, :index, :delete]

  end 
  devise_for :users

   root 'principal#index'

end

Fotolog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fotolog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
	<nav class="navbar navbar-default navbar-fixed-top">
      <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Fotolog</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-justified">

            <li class= "col-xs-6 col-sm-2 "><%= link_to "Inicio", root_path%></li>
            <% if user_signed_in? %>
              <% if current_user.is_admin? %>
              <li class= "col-xs-6 col-sm-2"><%= link_to "Lista de fotos", fotos_path %></li>
              <% else %>
              <li class= "col-xs-6 col-sm-2"><%= link_to "Mis fotos", fotos_path %></li>
              <li class= "col-xs-6 col-sm-2"><%= link_to "#{current_user.email}",   perfil_path(current_user.id)  %></li>

              <% end %>
            <li class= "col-xs-6 col-sm-2"><%= link_to "Lista de usuarios",  followers_path  %></li>

            <li class= "col-xs-6 col-sm-2"><%= link_to "Cerrar Sesion", destroy_user_session_path, :method => :delete  %></li>
      			<% else %>
      			<li class= "col-xs-6 col-sm-2"><%= link_to "Iniciar Sesion", new_user_session_path%></li>
      			<li class= "col-xs-6 col-sm-2"><%= link_to "Registrarse", new_user_registration_path %></li>
      			<% end %>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
	</header>
	<br>
	<br>
    <br>
    <div style="<%= "display:none;" if notice.nil? and alert.nil? %>"> 
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
    </div>


<%= yield %>

</body>
</html>