Fotolog/config/routes.rb
Rails.application.routes.draw do
  resources :followers, only: [:create, :destroy, :delete, :index]
  get '/perfil/:id', to: 'perfil#show', as: 'perfil'

  resources :fotos do 
    resources :coments, only: [:create, :destroy, :index, :delete]
    resources :calificacions, only: [:create, :destroy, :index, :delete]

  end 
  devise_for :users

   root 'principal#index'

end

Fotolog/app/models/coment.rb
class Coment < ActiveRecord::Base
  belongs_to :foto
  belongs_to :user
  before_create :set_time
  validates :texto_comentario, presence: true, length: {maximum: 200}
  validates :anonimo, presence: true

    def set_time
  		self.fecha_comentario=DateTime.now
  	end


end

Fotolog/app/controllers/coments_controller.rb
class ComentsController < ApplicationController
  before_action :set_coment, only: [:update, :destroy]
  before_action :set_foto
  before_action :authenticate_user!, only: [:index]
  before_action :authenticate_admin!, only: [:index]

  # GET /coments
  # GET /coments.json

  # POST /coments
  # POST /coments.json
  def index
    @coments = Coment.where("foto_id = ?", params[:foto_id])
  end


  def create
    @coment = Coment.new(coment_params)
    @coment.foto = @foto


    respond_to do |format|
      if @coment.save
        format.html { redirect_to @coment.foto, notice: 'El comentario fue creado con exito.' }
        format.json { render :show, status: :created, location: @coment }
        @coment.foto.agregar_comentarios

      else
        format.html { render :new}
        format.json { render json: @coment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coments/1
  # PATCH/PUT /coments/1.json
  def update
    respond_to do |format|
      if @coment.update(coment_params)
        format.html { redirect_to @coment.foto, notice: 'El comentario fue editado con exito.' }
        format.json { render :show, status: :ok, location: @coment }
      else
        format.html { render :edit }
        format.json { render json: @coment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coments/1
  # DELETE /coments/1.json
  def destroy
    @coment.destroy
    respond_to do |format|
      format.html { redirect_to @foto, notice: 'El comentario fue eliminado con exito.' }
      @coment.foto.borrar_comentarios
      format.json { head :no_content }
    end
  end

  private
    def set_foto
      @foto = Foto.find(params[:foto_id])
      
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_coment
      @coment = Coment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coment_params
      params.require(:coment).permit(:foto_id, :user_id, :fecha_comentario, :texto_comentario, :anonimo)
    end
end

Fotolog/app/helpers/coments_helper.rb
module ComentsHelper
end

Fotolog/app/views/coments/_form.html.erb
<%= form_for([@foto,@coment]) do |f| %>
  <% if @coment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coment.errors.count, "error") %> prohibited this coment from being saved:</h2>

      <ul>
      <% @coment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <%= f.hidden_field :anonimo, :value => current_user.email %>
  <% else %>
   <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :anonimo %>
  </div>
  <% end %>


  <div class="field">
    <%= f.label :texto_comentario %><br>
    <%= f.text_area :texto_comentario %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Fotolog/app/views/coments/edit.html.erb
<h1>Editing Coment</h1>

<%= render 'form' %>

<%= link_to 'Show', @coment %> |
<%= link_to 'Back', coments_path %>

Fotolog/app/views/coments/index.html.erb
<h1>Lista Comentarios</h1>

<table >
  <thead>
    <tr>
      <th>Id Foto </th>
      <th>User</th>
      <th>Fecha comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        <% @coments.each do |coment| %>

        <td><%= coment.foto_id %></td>
        <td><%= coment.anonimo %></td>
        <td><%= coment.fecha_comentario %></td>
        <td><%= link_to 'Eliminar', [coment.foto, coment], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
        <% end %>

  </tbody>
</table>

<br>

Fotolog/app/views/coments/new.html.erb
<h1>New Coment</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

Fotolog/app/views/coments/show.html.erb
<p>
  <strong>Foto:</strong>
  <%= @coment.foto %>
</p>

<p>
  <strong>User:</strong>
  <%= @coment.user %>
</p>

<p>
  <strong>Fecha comentario:</strong>
  <%= @coment.fecha_comentario %>
</p>

<p>
  <strong>Texto comentario:</strong>
  <%= @coment.texto_comentario %>
</p>

<p>
  <strong>Anonimo:</strong>
  <%= @coment.anonimo %>
</p>

<%= link_to 'Edit', edit_coment_path(@coment) %> |
<%= link_to 'Back', coments_path %>